name: eldorado_challenge
description: "El Dorado challenge app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  retrofit: ^4.7.0
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  intl: ^0.20.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cripto_currencies/
    - assets/fiat_currencies/
    - .env
